# setup-mongo-windows.ps1 — one-time MongoDB setup for Windows
# Run from the repo root:  .\scripts\weather\setup-mongo-windows.ps1
# Safe to re-run — all steps are idempotent.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ROOT = Resolve-Path "$PSScriptRoot\..\.."

Write-Host "`n=== Weathermen — MongoDB Setup ===" -ForegroundColor Cyan

# ── 1. Docker Desktop check / install ─────────────────────────────────────────
$dockerOk = $false
try { $null = docker info 2>&1; $dockerOk = $true } catch {}

if (-not $dockerOk) {
  Write-Host "`nDocker Desktop not found." -ForegroundColor Yellow

  # Check if winget is available
  $wingetOk = $false
  try { $null = winget --version 2>&1; $wingetOk = $true } catch {}

  if (-not $wingetOk) {
    Write-Host "winget is not available on this machine." -ForegroundColor Red
    Write-Host "Install Docker Desktop manually: https://docs.docker.com/desktop/install/windows-install/" -ForegroundColor Yellow
    Write-Host "Then re-run this script." -ForegroundColor Yellow
    exit 1
  }

  Write-Host "Installing Docker Desktop via winget (this may take a few minutes)..." -ForegroundColor Yellow
  winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements

  Write-Host "`nDocker Desktop installed." -ForegroundColor Green
  Write-Host "ACTION REQUIRED: Start Docker Desktop from the Start menu, wait for it to fully" -ForegroundColor Yellow
  Write-Host "load (whale icon in system tray stops animating), then re-run this script." -ForegroundColor Yellow
  exit 0
}

Write-Host "Docker Desktop: OK" -ForegroundColor Green

# ── 2. Generate MONGO_PASSWORD if not already in .env ─────────────────────────
$envFile = Join-Path $ROOT '.env'
if (-not (Test-Path $envFile)) {
  Write-Host "`n.env not found — copy .env.example to .env and fill in your values first." -ForegroundColor Red
  exit 1
}

$envContent = Get-Content $envFile -Raw

if ($envContent -notmatch 'MONGO_PASSWORD=\S') {
  # Generate 32-char alphanumeric password
  $chars = (65..90) + (97..122) + (48..57)
  $pw = -join ($chars | Get-Random -Count 32 | ForEach-Object { [char]$_ })
  $mongoUrl = "mongodb://ace:$pw@127.0.0.1:27017/ace_trading?authSource=admin"

  Add-Content $envFile "`n# ── MongoDB (auto-generated by setup-mongo-windows.ps1) ──────────────────────"
  Add-Content $envFile "MONGO_PASSWORD=$pw"
  Add-Content $envFile "MONGO_URL=$mongoUrl"
  Write-Host "MONGO_PASSWORD and MONGO_URL written to .env" -ForegroundColor Green
} else {
  Write-Host "MONGO_PASSWORD already set in .env — skipping" -ForegroundColor Cyan
}

# ── 3. Start MongoDB container ─────────────────────────────────────────────────
Set-Location $ROOT
Write-Host "`nStarting MongoDB container..."
docker compose up -d mongodb
if ($LASTEXITCODE -ne 0) {
  Write-Host "docker compose up failed. Check docker-compose.yml and Docker Desktop status." -ForegroundColor Red
  exit 1
}

# ── 4. Wait for healthy (up to 60s) ───────────────────────────────────────────
Write-Host "Waiting for MongoDB to become healthy..."
$attempts = 0
$status   = ''
do {
  Start-Sleep -Seconds 3
  $attempts++
  try { $status = docker inspect --format='{{.State.Health.Status}}' ace_mongodb 2>$null } catch { $status = '' }
} while ($status -ne 'healthy' -and $attempts -lt 20)

if ($status -ne 'healthy') {
  Write-Host "`nMongoDB did not become healthy after 60s." -ForegroundColor Red
  Write-Host "Check logs: docker logs ace_mongodb" -ForegroundColor Yellow
  exit 1
}
Write-Host "MongoDB healthy." -ForegroundColor Green

# ── 5. npm install ─────────────────────────────────────────────────────────────
Write-Host "`nInstalling npm dependencies..."
npm install
if ($LASTEXITCODE -ne 0) { Write-Host "npm install failed." -ForegroundColor Red; exit 1 }

# ── 6. Create indexes ──────────────────────────────────────────────────────────
Write-Host "`nCreating indexes..."
node scripts/migrate/create-indexes.js
if ($LASTEXITCODE -ne 0) { Write-Host "create-indexes.js failed." -ForegroundColor Red; exit 1 }

# ── 7. Import BTC + BZ trades ─────────────────────────────────────────────────
Write-Host "`nImporting BTC + BZ trades..."
node scripts/migrate/import-trades.js
if ($LASTEXITCODE -ne 0) { Write-Host "import-trades.js failed." -ForegroundColor Red; exit 1 }

# ── 8. Import state files (BTC, BZ, news, Discord bot) ────────────────────────
Write-Host "`nImporting state files..."
node scripts/migrate/import-state.js
if ($LASTEXITCODE -ne 0) { Write-Host "import-state.js failed." -ForegroundColor Red; exit 1 }

# ── 9. Import Weathermen data ──────────────────────────────────────────────────
Write-Host "`nImporting Weathermen data..."
node scripts/migrate/import-weathermen.js
if ($LASTEXITCODE -ne 0) { Write-Host "import-weathermen.js failed." -ForegroundColor Red; exit 1 }

# ── Done ───────────────────────────────────────────────────────────────────────
Write-Host "`n=== All done! MongoDB is ready. ===" -ForegroundColor Green
Write-Host ""
Write-Host "MongoDB starts automatically with Docker Desktop (restart: unless-stopped)."
Write-Host "To start it manually after a reboot if Docker Desktop is not running:"
Write-Host "  docker compose up -d mongodb" -ForegroundColor Cyan
Write-Host ""
Write-Host "Verify collections:"
Write-Host "  docker exec -it ace_mongodb mongosh -u ace -p `$env:MONGO_PASSWORD --authenticationDatabase admin ace_trading --eval `"db.weather_trades.countDocuments()`"" -ForegroundColor Cyan
